# Simple workflow for deploying static content to GitHub Pages
name: Deploy na AWS EC2

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "${{secrets.key}}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-98-83-156-176.compute-1.amazonaws.com "
            cd /var/www/html/PaginaEstaticaAWS && 
            sudo git pull "
     
